name             'webapp'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures webapp'
long_description 'Installs/Configures webapp'
version '0.1.0'

depends 'compat_resource' 
depends 'httpd', '~> 0.3.4'
